### ISSUE TITLE
Build Admin dashboard

### ISSUE THREAD

**Issue by overeha** [code4romania/monitorizare-vot-votanti-admin#11]
The application needs a dashboard for editors where they can:
- approve and/or reject incoming messages on the platform
- add or remove extra content pages in the platform
- edit the menu labels 
- upload and edit content on already existing pages. - related to https://github.com/code4romania/monitorizare-vot-votanti-client/issues/46
- keep an archive

**Comment by ciprian-chichirita** [comment]
pai si daca eu lucre la asta cum fac ca sa va dati seama ca eu sunt ala?

**Comment by ciprian-chichirita** [comment]
please add wireframe so we know what we should actually implement, this is way too boad for a one day job

**Comment by overeha** [comment]
WIP Wirreframes in here

![approved messages board](https://user-images.githubusercontent.com/45068169/51790541-6df80c00-219f-11e9-975b-fe0dd481eb5c.png)
![forms](https://user-images.githubusercontent.com/45068169/51790542-6fc1cf80-219f-11e9-9144-7ee114845acb.png)
![unread messages board](https://user-images.githubusercontent.com/45068169/51790543-751f1a00-219f-11e9-9407-4eef330c306c.png)
![users](https://user-images.githubusercontent.com/45068169/51790545-76504700-219f-11e9-9ccb-6d4c5f409f91.png)
![pages](https://user-images.githubusercontent.com/45068169/51790547-79e3ce00-219f-11e9-8404-315a79f5c545.png)

**Comment by aniri** [comment]
detailed in new issues
