### ISSUE TITLE
Admins can approve or reject messages

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-votanti-admin#13]
Add messages option in admin dashboard menu.

Admin can view messages list
Admin can approve or reject messages 
Admin can sort messages by unread / approved / rejected

Wireframes:
![approved messages board](https://user-images.githubusercontent.com/45068169/51790541-6df80c00-219f-11e9-975b-fe0dd481eb5c.png)

![unread messages board](https://user-images.githubusercontent.com/45068169/51790543-751f1a00-219f-11e9-9407-4eef330c306c.png)

Best practices

- codebase language should be English
- we :two_hearts: unit tests

**Comment by aniri** [comment]
assigned to @ Timofte Ciprian

**Comment by RaduCStefanescu** [comment]
This issue is moved permanently to the Client implementation, and is replaced by the following issue:
https://github.com/code4romania/monitorizare-vot-votanti-client/issues/63
Closing this one.
