### ISSUE TITLE
Admins can view available message forms

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-votanti-admin#14]
Add forms option in admin dashboard menu.

Admin can view forms list

![forms](https://user-images.githubusercontent.com/45068169/51790542-6fc1cf80-219f-11e9-9144-7ee114845acb.png)

Best practices

- codebase language should be English
- we :two_hearts: unit tests

**Comment by qwertypnk** [comment]
Iau eu asta

**Comment by RaduCStefanescu** [comment]
Moved to client repo, under this issue:
https://github.com/code4romania/monitorizare-vot-votanti-client/issues/78
I will close this one.
