### ISSUE TITLE
Admin can activate or deactivate pages

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-votanti-admin#17]
Admin views pages list.

Admin can activate or deactivate pages

![pages](https://user-images.githubusercontent.com/45068169/51790547-79e3ce00-219f-11e9-8404-315a79f5c545.png)

Depends on https://github.com/code4romania/monitorizare-vot-votanti-admin/issues/16

Best practices

- codebase language should be English
- we :two_hearts: unit tests

**Comment by RaduCStefanescu** [comment]
In progress @ Qwerty Pnk

**Comment by RaduCStefanescu** [comment]
Frontend implementation is moved to client repo:
https://github.com/code4romania/monitorizare-vot-votanti-client/issues/68
I will close this one.
