### ISSUE TITLE
Admin can delete pages

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-votanti-admin#18]
Admin views pages list.

Admin can delete pages

![pages](https://user-images.githubusercontent.com/45068169/51790547-79e3ce00-219f-11e9-8404-315a79f5c545.png)

Depends on https://github.com/code4romania/monitorizare-vot-votanti-admin/issues/16

Best practices

- codebase language should be English
- we :two_hearts: unit tests

**Comment by RaduCStefanescu** [comment]
In progress @ Qwerty Pnk

**Comment by RaduCStefanescu** [comment]
The backend implementation has been done and merged in https://github.com/code4romania/monitorizare-vot-votanti-api/pull/23
The frontend implementation is part of the client repo, and an issue is available here:
https://github.com/code4romania/monitorizare-vot-votanti-client/issues/68
This is part of migrating the Admin panel to the client repo. I will close this issue.
